[versions]
spring-boot = "3.5.3"
spring-management = "1.1.7"
#aspectJ-compiler = "9.1.0"

log4j = "2.25.0"
spring-log4j = "3.5.3"
log = "1.3.5"

aspectJ = "1.9.24"
#aspectJ-spring = "6.2.8"
servlet-api = "6.1.0"
thymeleaf = "3.1.3.RELEASE"

[libraries]
spring-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-acutator = {group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
junit = { group = "org.junit.platform", name = "junit-platform-launcher" }

#logging with spring is enough tricky
spring-log4j = { group = "org.springframework.boot", name = "spring-boot-starter-log4j2" }
log-commons = { group = "commons-logging", name = "commons-logging", version.ref = "log" }
log4j-spring-profile = { group = "org.apache.logging.log4j", name = "log4j-spring-boot" }

log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-layout = { group = "org.apache.logging.log4j", name = "log4j-layout-template-json", version.ref = "log4j" }

#to use aspectJ correctly
aspectJ-weaver = { group = "org.aspectj", name = "aspectjweaver", version.ref = "aspectJ" }
aspectJ-runtime = { group = "org.aspectj", name = "aspectjrt", version.ref = "aspectJ"}
#aspectJ-spring = { group = "org.springframework", name = "spring-aspects", version.ref = "aspectJ-spring" }

#to work with servlets from Tomcat
servlet-api = { group = "jakarta.servlet", name = "jakarta.servlet-api", version.ref = "servlet-api" }

#thymeleaf
thymeleaf = { group = "org.thymeleaf", name = "thymeleaf", version.ref = "thymeleaf" }
thymeleaf-spring = { group = "org.thymeleaf", name = "thymeleaf-spring6", version.ref = "thymeleaf"}

[bundles]
log = ["log4j-core", "log4j-api"]
spring-log = ["spring-log4j", "log4j-spring-profile", "log-commons"]
log-runtime = ["log4j-layout"]
thymeleaf = ["thymeleaf", "thymeleaf-spring"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-management = { id = "io.spring.dependency-management", version.ref = "spring-management" }
spring-thin-jar = { id = "org.springframework.boot.experimental.thin-launcher", version = "1.0.31.RELEASE" }
#aspectJ-compiler = { id = "io.freefair.lombok", version.ref = "aspectJ-compiler" }

#spring-boot-starter-actuator - starter for using spring boot's actuator which provides production ready features to help you monitor and manage your application